[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mpps"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]